apiVersion: v1
kind: Namespace
metadata:
  name: ops-atlas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-atlas
  namespace: ops-atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-atlas
  template:
    metadata:
      labels:
        app: ops-atlas
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: web
          image: 192.168.8.191:5000/ops-atlas:0.1-arm64
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ops-atlas
  namespace: ops-atlas
spec:
  selector:
    app: ops-atlas
  ports:
    - port: 80
      targetPort: 80
