apiVersion: v1
kind: Namespace
metadata:
  name: ops-atlas
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ops-atlas
  namespace: ops-atlas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ops-atlas
  template:
    metadata:
      labels:
        app: ops-atlas
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
        - name: web
          image: ghcr.io/shellback1998/ops-atlas@sha256:3d057278b9b07d9f5a74a29f2bdd1e3a632cd3b6426aa244c6095094d87255ec
          env:
            - name: DEPLOYMENT_TARGET
              value: turing-pi-k3s
            - name: APP_VERSION
              value: "0.7"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ops-atlas
  namespace: ops-atlas
spec:
  selector:
    app: ops-atlas
  ports:
    - port: 80
      targetPort: 8080
